# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=15, verbose_name='IP地址')),
                ('hostname', models.CharField(blank=True, max_length=20, verbose_name='机器名字')),
                ('run_neicun', models.IntegerField(blank=True, verbose_name='运行内存')),
                ('disk_neicun', models.IntegerField(blank=True, verbose_name='硬盘内存')),
                ('os', models.CharField(blank=True, max_length=20, verbose_name='操作系统')),
                ('desc', models.TextField(blank=True, verbose_name='机器描述')),
            ],
            options={
                'db_table': 'NodeMess',
            },
        ),
    ]
