# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=15, verbose_name='用户名')),
                ('time', models.TimeField(verbose_name='时间')),
                ('sessionname', models.CharField(max_length=20, verbose_name='事务名')),
                ('context', models.TextField(verbose_name='提交的内容')),
            ],
            options={
                'db_table': 'session',
            },
        ),
    ]
