# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='context',
            field=models.TextField(blank=True, verbose_name='提交的内容'),
        ),
        migrations.AlterField(
            model_name='session',
            name='sessionname',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='事务名'),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(blank=True, verbose_name='时间'),
        ),
    ]
