# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-20 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='context',
            field=models.TextField(blank=True, verbose_name=b'\xe6\x8f\x90\xe4\xba\xa4\xe7\x9a\x84\xe5\x86\x85\xe5\xae\xb9'),
        ),
        migrations.AlterField(
            model_name='session',
            name='sessionname',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name=b'\xe4\xba\x8b\xe5\x8a\xa1\xe5\x90\x8d'),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.DateTimeField(blank=True, verbose_name=b'\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
